extends Node2D

class_name Enemy_Enums

enum enemy_types_enum{
	avatar,
	goblin,
	goblin_wizard,
	monkey,
	robber,
	human_wizard,
	human_sorcerer,
	human_jack,
	human_queen,
	human_king,
	rat,
	bat,
	dog,
	snake,
	spider_tiny,
	spider_big,
	eye,
	slime_tiny,
	slime_big,
	vines,
	slime_boss,
	goblin_boss,
	undead,
	demon,
	vampire,
	lich,
	bull_god,
	golem_god,
	alien_god,
	dragon_god
}
const enemy_types_dict = {
	enemy_types_enum.avatar: Avatar,
	enemy_types_enum.goblin: Goblin
#	enemy_types_enum.goblin_wizard: Goblin_Wizard,
#	enemy_types_enum.monkey: Monkey,
#	enemy_types_enum.robber: Robber,
#	enemy_types_enum.human_wizard: Human_Wizard,
#	enemy_types_enum.human_sorcerer: Human_Sorcerer,
#	enemy_types_enum.human_jack: Human_Jack,
#	enemy_types_enum.human_queen: Human_Queen,
#	enemy_types_enum.human_king: Human_King,
#	enemy_types_enum.rat: Rat,
#	enemy_types_enum.bat: Bat,
#	enemy_types_enum.dog: Dog,
#	enemy_types_enum.snake: Snake,
#	enemy_types_enum.spider_tiny: Spider_Tiny,
#	enemy_types_enum.spider_big: Spider_Big,
#	enemy_types_enum.eye: Eye,
#	enemy_types_enum.slime_tiny: Slime_Tiny,
#	enemy_types_enum.slime_big: Slime_Big,
#	enemy_types_enum.vines: Vines,
#	enemy_types_enum.slime_boss: Slime_Boss,
#	enemy_types_enum.goblin_boss: Goblin_Boss,
#	enemy_types_enum.undead: Undead,
#	enemy_types_enum.demon: Demon,
#	enemy_types_enum.vampire: Vampire,
#	enemy_types_enum.lich: Lich,
#	enemy_types_enum.bull_god: Bull_God,
#	enemy_types_enum.golem_god: Golem_God,
#	enemy_types_enum.alien_god: Alien_God,
#	enemy_types_enum.dragon_god: Dragon_God
}
